# Generated by Django 3.0.3 on 2020-03-10 12:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='spending',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateField(verbose_name=datetime.datetime(2020, 3, 10, 12, 15, 50, 685448, tzinfo=utc)),
        ),
    ]
