# Generated by Django 3.0.3 on 2020-03-24 10:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200311_1238'),
    ]

    operations = [
        migrations.CreateModel(
            name='LastUpdateDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_update', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateField(verbose_name=datetime.datetime(2020, 3, 24, 10, 1, 11, 782840, tzinfo=utc)),
        ),
    ]
