# Generated by Django 3.0.3 on 2020-03-27 15:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20200327_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='expenses',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateField(verbose_name=datetime.datetime(2020, 3, 27, 15, 6, 14, 390446, tzinfo=utc)),
        ),
    ]
