# Generated by Django 3.0.3 on 2020-03-29 12:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20200327_1616'),
    ]

    operations = [
        migrations.RenameField(
            model_name='budget',
            old_name='end_date',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='budget',
            name='start_date',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateField(verbose_name=datetime.datetime(2020, 3, 29, 12, 57, 47, 129695, tzinfo=utc)),
        ),
    ]
