# Generated by Django 3.0.5 on 2020-04-10 09:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20200329_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='is_income',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateField(verbose_name=datetime.datetime(2020, 4, 10, 9, 40, 18, 419441, tzinfo=utc)),
        ),
    ]
