# Generated by Django 3.0.5 on 2020-04-10 11:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20200410_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateField(verbose_name=datetime.datetime(2020, 4, 10, 11, 13, 33, 916646, tzinfo=utc)),
        ),
    ]
