# Generated by Django 3.0.5 on 2020-04-14 12:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20200410_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateField(verbose_name=datetime.datetime(2020, 4, 14, 12, 53, 43, 520046, tzinfo=utc)),
        ),
    ]
