# Generated by Django 3.0.5 on 2020-04-15 08:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20200414_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='bank',
            field=models.CharField(max_length=24),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateField(verbose_name=datetime.datetime(2020, 4, 15, 8, 2, 25, 295604, tzinfo=utc)),
        ),
    ]
